version: '3'
services:
  app:
    build: .
    ports:
      - "3456:3456"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: